---
name: haskell wordpuzzle

on: # yamllint disable-line rule:truthy
  push:
    branches: ["**"]
    tags: ["v*"]
  check_run:
    types: [rerequested, requested_action]
# yamllint enable

env:
  STACK_ROOT: ${{ github.workspace }}/.stack-work

jobs:
  build:
    permissions:
      contents: write
      pages: write
      id-token: write

    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STACK_ROOT }}
          key: ${{ github.ref }}

      - name: build
        run: stack build --pedantic --no-test

      - name: test
        run: stack test --coverage

      - name: bench
        run: |
          stack bench --benchmark-arguments '-o ${{ env.STACK_ROOT }}/benchmark.html'

      - name: haddock
        if: github.ref == 'refs/heads/master'
        run: |
          stack haddock --haddock-hyperlink-source
          mv $(stack path --local-doc-root)/ public/
          mv ${{ env.STACK_ROOT }}/benchmark.html public/

      - name: publish
        if: success() && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public

      - name: Package release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          EXE_PATH=$(find $(stack path --local-install-root)/bin -name wordpuzzle | head -n 1)
          cp "$EXE_PATH" wordpuzzle
          tar -czf wordpuzzle-release.tar.gz wordpuzzle dictionary

      - name: Create/Update Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: wordpuzzle-release.tar.gz
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
