---
name: cicd

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - "**"
    tags:
      - "v*"
  pull_request:
# yamllint enable

env:
  STACK_ROOT: ${{ github.workspace }}/.stack-work

jobs:
  cicd:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STACK_ROOT }}
          key: stack-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ github.ref }}
            stack-{{ hashFiles('stack.yaml') }}

      - name: build
        run: stack build --pedantic --no-test

      - name: test
        run: stack test --coverage

      - name: benchmark
        if: >
          github.ref == 'refs/heads/master'
          && github.event_name == 'push'
        run: stack bench --benchmark-arguments '-o ${{ env.STACK_ROOT }}/benchmark.html'

      - name: pages
        if: >
          github.ref == 'refs/heads/master'
          && github.event_name == 'push'
        run: |
          stack haddock --haddock-hyperlink-source
          mv $(stack path --local-doc-root)/ public/
          mv ${{ env.STACK_ROOT }}/benchmark.html public/

      - name: upload pages
        if: >
          github.ref == 'refs/heads/master'
          && github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: package release
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          EXE_PATH=$(find $(stack path --local-install-root)/bin -name wordpuzzle | head -n 1)
          cp "$EXE_PATH" wordpuzzle
          tar -czf wordpuzzle-release.tar.gz wordpuzzle dictionary

      - name: upload release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: wordpuzzle-release.tar.gz
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
